name: my_flutter_app
description: A real-time multiplayer reaction game.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  web_socket_channel: ^3.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: Cubic
      fonts:
        - asset: assets/fonts/Cubic_11_1.100_R.ttf
  assets:
    - assets/avatars/avatar1.png
    - assets/avatars/avatar2.png
    - assets/avatars/avatar3.png
